parameters:
  job: osx
  matrix:
    Production: {}
  poolName: DotNetCore-Mac
  poolDemands: Agent.OS -equals Darwin

jobs:
- job: ${{ parameters.job }}
  strategy:
    matrix: ${{ parameters.matrix }}
  pool:
    name: ${{ parameters.poolName }}
    demands: ${{ parameters.poolDemands }}
  timeoutInMinutes: 240
  variables:
    # Prefix to distinguish artifacts from different legs.
    artifactName: ${{ format('$(type) {0}', parameters.job) }}
    logsDirectory: $(Build.ArtifactStagingDirectory)/logs
    SOURCE_BUILD_SKIP_SUBMODULE_CHECK: true
    # Default type, can be overridden by matrix legs.
    type: Production

  steps:
  - checkout: self
    clean: true

  - script: |
      ./clean.sh -a
      # Make sure submodules from other branches are removed: pass extra f.
      git clean -xdff
    displayName: Clean

  - template: ../steps/calculate-config-flags-linux.yml

  - script: |
      ( set -o posix; set )
    displayName: Print all variables in environment

  - template: ../steps/init-submodules-sh.yml

  # Build source-build.
  - script: |
      set -x
      ./build.sh \
        /p:Configuration=$(sb.configuration) \
        /p:PortableBuild=$(sb.portable) \
        /p:FailOnPrebuiltBaselineError=true \
        /p:ProdConBlobFeedUrlPrefix=$(prodConBlobFeedUrlPrefix)
    displayName: Build source-build
    timeoutInMinutes: 150

  # Run smoke tests.
  - script: |
      set -x
      ./build.sh \
        /t:RunSmokeTest \
        /p:Configuration=$(sb.configuration) \
        /p:ProdConBlobFeedUrlPrefix=$(prodConBlobFeedUrlPrefix)
    displayName: Run smoke-test

  - script: |
      set -x
      # Clean up previous build's staging dir, in case VSTS didn't do it.
      rm -rf "$(logsDirectory)"
      # Copy all these files to the logs dir, preserving relative path.
      mkdir -p "$(logsDirectory)"
      find . \( \
        -path './bin/*-report/*' -o \
        -iname '*.binlog' -o \
        -iname '*.log' \) \
        -exec rsync -R {} "$(logsDirectory)" \;
    displayName: Copy logs to staging directory
    condition: always()
    continueOnError: true

  # Publish artifacts.
  - task: PublishBuildArtifacts@1
    displayName: Publish Logs artifact
    condition: always()
    continueOnError: true
    inputs:
      PathtoPublish: $(logsDirectory)
      ArtifactName: Logs $(artifactName)
      ArtifactType: Container
