blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/dotnet/source-build/discussions
    about: Is your issue perhaps more of a discussion or question? Please start a new discussion.
  - name: Issue with .NET runtime or core .NET libraries
    url: https://github.com/dotnet/runtime/issues/new/choose
    about: Please open issues relating to the .NET runtime or core .NET libraries in dotnet/runtime.
  - name: Issue with ASP.NET Core
    url: https://github.com/dotnet/efcore/issues/new/choose
    about: Please open issues relating to ASP.NET Core in dotnet/aspnetcore.
  - name: Issue with .NET SDK
    url: https://github.com/dotnet/sdk/issues/new/choose
    about: Please open issues relating to the .NET SDK itself in dotnet/sdk.
  - name: Issue with Roslyn compiler
    url: https://github.com/dotnet/roslyn/issues/new/choose
    about: Please open issues relating to the Roslyn .NET compiler in dotnet/roslyn.
  - name: Issue with other .NET components
    url: https://github.com/dotnet/core/blob/master/Documentation/core-repos.md
    about: Having issues with other .NET components? Please find the correct location where to open an issue.
