trigger: none
pr: none

pool:
  name: NetCore1ESPool-Svc-Internal
  demands: ImageOverride -equals 1es-ubuntu-2004

resources:
  pipelines:
  - pipeline: dotnet-staging-pipeline-resource
    source: Stage-DotNet-Test

parameters:
- name: useSpecificPipelineRunIDs
  displayName: Use specific pipeline run IDs
  type: boolean
  default: false
- name: dotnetDotnetRunID
  displayName: Specific dotnet-dotnet run ID
  type: string
  default: '200XXXX'
- name: releaseBranchName
  displayName: '[Preview releases only] Release branch name, for example release/8.0.1xx-preview1'
  type: string
  default: ' '
- name: verifyBuildSuccess
  displayName: Verify that associated pipeline runs succeeded
  type: boolean
  default: true

variables:
- template: templates/variables/installer-pipelines.yml
# we strip spaces as the default value for releaseBranchName has a space to make it non-required
- name: ReleaseBranchName
  value: ${{ replace(parameters.releaseBranchName, ' ', '') }}

jobs:
- job: SourceBuildPreRelease
  displayName: Source Build Pre-Release

  steps:
  - template: templates/steps/get-build-info.yml
    parameters:
      dotnetStagingPipelineResource: dotnet-staging-pipeline-resource
      getAssociatedPipelineRuns: true
      useSpecificPipelineRunIDs: ${{ parameters.useSpecificPipelineRunIDs }}
      dotnetDotnetRunID: ${{ parameters.dotnetDotnetRunID }}
      releaseBranchName: ${{ variables.ReleaseBranchName }}
      verifyBuildSuccess: ${{ parameters.verifyBuildSuccess }}
