trigger: none
pr: none

pool:
  name: NetCore1ESPool-Svc-Internal
  demands: ImageOverride -equals 1es-ubuntu-2004

resources:
  pipelines:
  - pipeline: dotnet-staging-pipeline-resource
    source: Stage-DotNet

parameters:
  - name: useSpecificPipelineRunIDs
    displayName: Use Specific Pipeline Run IDs
    type: boolean
    default: false
  - name: dotnetInstallerOfficialRunID
    displayName: dotnet-installer-official-ci run ID
    type: string
    default: '200XXXX'
  - name: dotnetInstallerTarballBuildRunID
    displayName: dotnet-installer-source-build-tarball-build run ID
    type: string
    default: '200XXXX'

variables:
- template: templates/installer-pipeline-variables.yml
- group: DotNet-MSRC-Storage
- name: storageAccountName
  value: 'dotnetclimsrc'
- name: blobContainerName
  value: 'source-build'
- name: blobContainerUploadBaseFilePath
  value: 'Dev'

jobs:
- job: UploadSourceTarballJob
  displayName: Upload Source Tarball

  steps:
  - template: templates/get-build-info.yml
    parameters:
      stageDotNetPipelineResource: dotnet-staging-pipeline-resource
      getAssociatedPipelineRuns: true
      useSpecificPipelineRunIDs: ${{ parameters.useSpecificPipelineRunIDs }}
      dotnetInstallerOfficialRunID: ${{ parameters.dotnetInstallerOfficialRunID }}
      dotnetInstallerTarballBuildRunID: ${{ parameters.dotnetInstallerTarballBuildRunID }}

  - task: DownloadPipelineArtifact@2
    name: DownloadSourceTarballStep
    displayName: Download Source Tarball
    inputs:
      source: 'specific'
      artifact: 'BlobArtifacts'
      patterns: 'BlobArtifacts/dotnet-sdk-source-$(SdkVersion).tar.gz'
      project: 'internal'
      pipeline: $(installerOfficialCiPipelineId)
      runVersion: 'specific'
      runId: $(InstallerOfficialRunId)

  - script: |
      set -euxo pipefail
      az config set extension.use_dynamic_install=yes_without_prompt

      source_tarball_upload_path="$(blobContainerUploadBaseFilePath)/$(ReleaseChannel)/$(RuntimeVersion)-$(SdkVersion)"
      source_tarball_filename="dotnet-sdk-source-$(SdkVersion).tar.gz"
      az storage blob upload --account-name "$(storageAccountName)" --container-name "$(blobContainerName)" --file "$(PIPELINE.WORKSPACE)/${source_tarball_filename}" --name "${source_tarball_upload_path}/${source_tarball_filename}"
    name: UploadSourceTarballStep
    displayName: Upload Source Tarball
    env:
      AZURE_STORAGE_KEY: $(dotnetclimsrc-access-key)
