aliveStatusCodes:
  - 200
  - 406
dirs:
  - .
  - .github
excludedDirs:
  - eng/readme-templates
ignorePatterns:
  - pattern: "^https://github.com/dotnet/sdk/tree/main/src/SourceBuild/patches"
  - pattern: "^https://dotnetcli.blob.core.windows.net/source-built-artifacts/sdks/"
  - pattern: "^https://dotnetcli.blob.core.windows.net/source-built-artifacts/assets/"
  - pattern: "^https://www.reddit.com/r/archlinux/comments/cx64r5/the_state_of_net_core_on_arch/"
useGitIgnore: true
