parameters:
  name: ''
  dependsOn: []
  matrix:
    Production: {}
  jobParameters: {}

stages:
- ${{ each matrixPair in parameters.matrix }}:
  - stage: ${{ parameters.name }}_${{ replace(coalesce(matrixPair.value.type, 'Production'), ' ', '_') }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
    - template: ${{ parameters.jobTemplateName }}
      parameters:
        ${{ insert }}: ${{ parameters.jobParameters }}
        job: ${{ parameters.name }}_${{ replace(coalesce(matrixPair.value.type, 'Production'), ' ', '_') }}
        buildTypeName: ${{ matrixPair.key }}
        type: ${{ matrixPair.value.type }}