steps:
- script: |
    setvariable() {
      echo "Setting '$1' to '$2'"
      echo "##vso[task.setvariable variable=$1;]$2"
    }

    echo 'Setting up default configuration variables'

    setvariable sb.configuration Release
    setvariable sb.portable false
    setvariable sb.tarball false
    setvariable sb.tarballOffline false

    echo "Setting up configuration variables for CI type '$TYPE'"

    for x in $TYPE; do
      case $x in
        Debug|Release)
          setvariable sb.configuration $x
          ;;

        Portable)
          setvariable sb.portable true
          ;;

        Online)
          setvariable sb.tarball true
          ;;
        Offline)
          setvariable sb.tarball true
          setvariable sb.tarballOffline true
          ;;
      esac
    done
  displayName: Calculate config flags
