trigger:
- release/5.0
- internal/release/5.0

pr:
- release/5.0
- internal/release/5.0

stages:
- template: matrix.yml
  parameters:
    windowsPoolName: NetCoreInternal-Pool
    windowsQueueName: buildpool.windows.10.amd64.vs2017
