# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

jobs:
- template: ../jobs/ci-linux.yml
  parameters:
    job: centos71
    imageName: microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416
    matrix:
      Production: {}
      Online: { type: Online }
      Online Portable: { type: Online Portable }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../jobs/ci-linux.yml
  parameters:
    job: debian82
    imageName: microsoft/dotnet-buildtools-prereqs:debian-8.2-4e6e894-20181023212416
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }

- template: ../jobs/ci-linux.yml
  parameters:
    job: ubuntu1604
    imageName: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-c103199-20180628134544

- template: ../jobs/ci-osx.yml
