# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

jobs:
- template: ../jobs/ci-linux.yml
  parameters:
    job: centos71
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
    reportPrebuiltLeaks: false
    matrix:
      Production: { generatePrebuiltBurndown: true }
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../jobs/ci-linux.yml
  parameters:
    job: debian9
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-c103199-20180628122423
    matrix:
      Production: {}
      Online: { type: Online }

- template: ../jobs/ci-linux.yml
  parameters:
    job: fedora29
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-29-98b4f89-20190506161422
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../jobs/ci-linux.yml
  parameters:
    job: ubuntu1604
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-edee7e7-20190503204407

- template: ../jobs/ci-local.yml
  parameters:
    job: osx
    pool:
      name: Hosted macOS
    scriptPrefix: ./
    scriptSuffix: .sh
    setupMac: true
