# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

jobs:
# - template: ../jobs/ci-linux.yml
#   parameters:
#     job: centos71
#     imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
#     reportPrebuiltLeaks: false
#     matrix:
#       Production: { generatePrebuiltBurndown: true, runUnitTests: true }
#       Online: { type: Online }
#       Offline: { type: Offline }
#       Offline Portable: { type: Offline Portable }

- template: ../jobs/ci-linux_bootstrap.yml
  parameters:
    job: centos71_BootStrap
    # dependsOn: centos71
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
    matrix:
      Offline: { type: Offline }

# - template: ../jobs/ci-linux.yml
#   parameters:
#     job: debian9
#     imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-d61254f-20190807161114
#     matrix:
#       Production: {}
#       Online: { type: Online }

# - template: ../jobs/ci-linux.yml
#   parameters:
#     job: fedora30
#     imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-38e0f29-20191126135223
#     matrix:
#       Production: {}
#       Online: { type: Online }
#       Offline: { type: Offline }
#       Offline Portable: { type: Offline Portable }

# - template: ../jobs/ci-linux.yml
#   parameters:
#     job: ubuntu1804
#     imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-f90bc20-20180320154721

# - template: ../jobs/ci-local.yml
#   parameters:
#     job: osx
#     pool:
#       name: Hosted macOS
#     scriptPrefix: ./
#     scriptSuffix: .sh
#     setupMac: true
