# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Int-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

jobs:
- template: ../jobs/ci-linux.yml
  parameters:
    job: centos71
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-359e48e-20200313130914
    reportPrebuiltLeaks: true
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../jobs/ci-linux.yml
  parameters:
    job: debian9
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-bfcd90a-20200121150012
    matrix:
      Production: {}
      Online: { type: Online }

- template: ../jobs/ci-linux.yml
  parameters:
    job: fedora30
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-bfcd90a-20200324132732
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../jobs/ci-linux.yml
  parameters:
    job: ubuntu1804
    imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-85814b7-20200324125103

- template: ../jobs/ci-local.yml
  parameters:
    job: osx
    pool:
      name: Hosted macOS
    scriptPrefix: ./
    scriptSuffix: .sh
    setupMac: true

- template: ../jobs/ci-local.yml
  parameters:
    job: windows
    pool:
      name: ${{ parameters.windowsPoolName }}
      queue: ${{ parameters.windowsQueueName }}
    scriptPrefix: ''
    scriptSuffix: .cmd
    setupWindows: true
    skipSmokeTest: true
    failOnPrebuiltBaselineError: false
