# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

stages:
- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: centos71
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
      reportPrebuiltLeaks: false
    matrix:
      Production: { generatePrebuiltBurndown: true, runUnitTests: true }
      Online: { type: Online BaseTarball }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux_bootstrap.yml
    name: centos71_BootStrap
    dependsOn: centos71_Offline
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
    matrix:
      Offline: { type: Offline }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: centos8
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-daa5116-20200325130212
      reportPrebuiltLeaks: false
      systemLibunwind: false
    matrix:
      Production: { generatePrebuiltBurndown: true, runUnitTests: true }
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: debian9
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-d61254f-20190807161114
      cleanAptGet: true
    matrix:
      Production: {}
      Online: { type: Online }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: fedora30
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-38e0f29-20191126135223
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: ubuntu1804
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20200918145614-047508b
      cleanAptGet: true

# Prepare artifacts in all situations but public PR validation.
- ${{ if not(and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'))) }}:
  - template: ../stages/prepare-artifacts.yml
    parameters:
      # Gather from all jobs that have offline in the matrix. This also defines dependencies.
      gatherJobs:
      - job: centos71_Offline
      - job: centos8_Offline
      - job: debian9_Online
      - job: fedora30_Offline
      - job: rhel7_x64_Offline
      - job: rhel8_x64_Offline
      - job: rhel8_arm64_Offline
      gatherPortableJob: centos71_Offline_Portable

# RHEL builds only internal
- ${{ if not(and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'))) }}:
  - template: ../stages/stage-jobs-matrix.yml
    parameters:
      jobTemplateName: ../jobs/ci-local.yml
      name: rhel8_arm64
      jobParameters:
        pool:
          name: DotNet-SourceBuild-Internal
          demands:
          - Agent.OSArchitecture -equals ARM64
          - rhel -equals 8
        scriptPrefix: ./
        scriptSuffix: .sh
      matrix:
        Production: {}
        Offline: { type: Offline }
  - template: ../stages/stage-jobs-matrix.yml
    parameters:
      jobTemplateName: ../jobs/ci-local.yml
      name: rhel7_x64
      jobParameters:
        pool:
          name: DotNet-SourceBuild-Internal
          demands:
          - Agent.OSArchitecture -equals X64
          - rhel -equals 7
        scriptPrefix: ./
        scriptSuffix: .sh
      matrix:
        Offline: { type: Offline }
  - template: ../stages/stage-jobs-matrix.yml
    parameters:
      jobTemplateName: ../jobs/ci-local.yml
      name: rhel8_x64
      jobParameters:
        pool:
          name: DotNet-SourceBuild-Internal
          demands:
          - Agent.OSArchitecture -equals X64
          - rhel -equals 8
        scriptPrefix: ./
        scriptSuffix: .sh
        useSystemLibunwind: true
      matrix:
        Offline: { type: Offline }
