# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

stages:
- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: centos71
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-359e48e-20200313130914
      reportPrebuiltLeaks: true
    matrix:
# Temporarily disable unit tests until entire product builds.
# See https://github.com/dotnet/source-build/issues/1549
      Production: { generatePrebuiltBurndown: true, runUnitTests: false }
      Online: { type: Online BaseTarball }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux_bootstrap.yml
    name: centos71_BootStrap
    dependsOn: centos71_Offline
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-359e48e-20200313130914
    matrix:
      Offline: { type: Offline }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: centos8
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-source-build-20200402192642-9e679d4
      reportPrebuiltLeaks: true
      systemLibunwind: false
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: debian9
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-d61254f-20190807161114
    matrix:
      Production: {}
      Online: { type: Online }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: fedora30
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-bfcd90a-20200324132732
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: fedora31
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-31-02f7c7e-20200324132728
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: ubuntu1804
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-source-build-20200401093015-ed32d26

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-local.yml
    name: osx
    jobParameters:
      pool:
        name: Hosted macOS
      scriptPrefix: ./
      scriptSuffix: .sh
      setupMac: true

# RHEL builds only internal
- ${{ if not(and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'))) }}:
  - template: ../stages/stage-jobs-matrix.yml
    parameters:
      jobTemplateName: ../jobs/ci-local.yml
      name: rhel7_x64
      jobParameters:
        pool:
          name: DotNet-SourceBuild-Internal
          demands:
          - Agent.OSArchitecture -equals X64
          - rhel -equals 7
        scriptPrefix: ./
        scriptSuffix: .sh
      matrix:
        Offline: { type: Offline }
  - template: ../stages/stage-jobs-matrix.yml
    parameters:
      jobTemplateName: ../jobs/ci-local.yml
      name: rhel8_x64
      jobParameters:
        pool:
          name: DotNet-SourceBuild-Internal
          demands:
          - Agent.OSArchitecture -equals X64
          - rhel -equals 8
        scriptPrefix: ./
        scriptSuffix: .sh
        useSystemLibunwind: true
      matrix:
        Offline: { type: Offline }

# Prepare artifacts in all situations but public PR validation.
- ${{ if not(and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'))) }}:
  - template: ../stages/prepare-artifacts.yml
    parameters:
      # Gather from all jobs that have offline in the matrix. This also defines dependencies.
      gatherJobs:
      - job: centos71_Offline
      - job: centos8_Offline
      - job: debian9_Online
      - job: fedora31_Offline
      - job: rhel7_x64_Offline
      - job: rhel8_x64_Offline
      gatherPortableJob: centos71_Offline_Portable
