# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

stages:
- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-local.yml
    name: osx
    jobParameters:
      pool:
        name: Hosted macOS
      scriptPrefix: ./
      scriptSuffix: .sh
      setupMac: true

# Prepare artifacts in all situations but public PR validation.
- ${{ if not(and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'))) }}:
  - template: ../stages/prepare-artifacts.yml
    parameters:
      # Gather from all jobs that have offline in the matrix. This also defines dependencies.
      gatherJobs:
      - job: centos71_Offline
      - job: centos8_Offline
      - job: debian9_Online
      - job: fedora31_Offline
      gatherPortableJob: centos71_Offline_Portable
