# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  windowsPoolName: NetCorePublic-Int-Pool
  windowsQueueName: buildpool.windows.10.amd64.vs2017.open

stages:
- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: centos71
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-359e48e-20200313130914
      reportPrebuiltLeaks: true
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: debian9
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-bfcd90a-20200121150012
    matrix:
      Production: {}
      Online: { type: Online }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: fedora30
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-bfcd90a-20200324132732
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-linux.yml
    name: ubuntu1804
    jobParameters:
      imageName: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-85814b7-20200324125103

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-local.yml
    name: osx
    jobParameters:
      pool:
        name: Hosted macOS
      scriptPrefix: ./
      scriptSuffix: .sh
      setupMac: true

- template: ../stages/stage-jobs-matrix.yml
  parameters:
    jobTemplateName: ../jobs/ci-local.yml
    name: windows
    jobParameters:
      pool:
        name: ${{ parameters.windowsPoolName }}
        queue: ${{ parameters.windowsQueueName }}
      scriptPrefix: ''
      scriptSuffix: .cmd
      setupWindows: true
      skipSmokeTest: true
      failOnPrebuiltBaselineError: false
